---
title: "Como pensar cientificamente?"
---

::: nota-secundaria
Roteiro de aula elaborado no RStudio com o auxílio da inteligência artificial ChatGPT e supervisionado pelo professor antes de sua publicação.
:::

## Contextualização

bla bla bla

Ao final deste encontro e com base na leitura indicada, espera-se que você seja capaz de:

- *bla bla *

::: leitura
Leitura indicada:

**Racionalidade científica: saindo do piloto automático** (p. 31-35), capítulo do livro *Fundamentos de metodologia científica: teoria da ciência e iniciação à pesquisa*, de José Carlos Kochë
:::

## Aprendizagem prática











::: proxima-aula
[Para a próxima aula:]{.proxima-aula-title}

-   **Leia** o texto **Conhecimento científico** (p. 15-16), capítulo do livro *Afinal o que é ciência?... e o que não é*, de André Demambre Bacchi. Disponível na Minha Biblioteca.

- **Leia** também **Observe, test, reflect: A better life with the scientific method**, artigo de Santiago Gisler publicado pela *Ivory Embassy*. Disponível em: https://ivoryembassy.com/the-scientific-method/.
:::
