# Leitura e escrita acadêmicas[^1]

[^1]:<sub>Roteiro de aula elaborado com o auxílio da inteligência artificial ChatGPT, revisado e avaliado pelo autor antes de sua publicação.</sub>

## Objetivos de aprendizagem

Ao final deste encontro e com base na leitura indicada, espera-se que você seja capaz de:

- Reconhecer as características do pensamento científico, diferenciando-o de outras formas de pensar e compreender sua relevância na construção do saber universitário.

<div class="section" style="padding:1em; background-color:#F5F5F5; color:#000000;">
  <em>Leitura indicada:</em> <br/>
  <strong>Think like a scientist: The power of a scientific mindset</strong>, postagem do blog <em>Ivory Embassy</em>, por Santiago Gisler.
  
[Acesso à leitura obrigatória](https://ivoryembassy.com/scientific-mindset/)


</div>

## Introdução


>"O universo acadêmico constitui-se em torno de saberes escritos." p. 11

>"(...) imperativo não apenas que professores pesquisadores prestem contas de seus estudos por meio de publicações, mas que toda a comunidade acadêmica o faça." p. 12

>"(...) os alunos de graduação são cada vez mais cobrados tanto para faze-rem parte da iniciação científica como para realizarem produções textuais ao longo do curso superior. Portanto, também os graduandos precisam apresentar resultados escritos, o que demanda igualmente grande quantidade de leitura." (p. 12)

>"(...) o ensino superior se centra na produção contínua e intensa de conhecimento" (p. 13)

## Você sabe escrever e ler cientificamente?

#### Aplicação de teste diagnóstico