# Análise e Expressão Textual

## Ementa
Abordar os paradigmas textuais e científicos na produção da escrita científica, a intertextualidade como elemento de linguagem no contexto da textualidade e da oralidade e da visualidade, a coesão e coerência textual como elemento estruturador da linguagem acadêmica, o estilo como mediador entre forma e conteúdo na produção do conhecimento, a interdisciplinaridade como estética da linguagem.

## Competência a ser desenvolvida
Compreender e aplicar os princípios da escrita científica a partir da análise crítica de paradigmas textuais e científicos, do uso consciente da intertextualidade, da coesão, da coerência e do estilo acadêmico, desenvolvendo a capacidade de produzir textos interdisciplinares e linguisticamente consistentes que reflitam a construção do conhecimento no contexto universitário.

## Encontros

### 14/04/2025 (Seg)
- Apresentação da disciplina
- Como se organiza o sistema acadêmico brasileiro?
  - Leitura: "Entendendo a organização do sistema acadêmico brasileiro", capítulo do livro "Guia do trabalho científico: do projeto à redação final", de Celso Ferrarezi Jr.



### 17/04/2025 (Qui)
- O que é pensamento científica?
  - Leitura: "Think like a scientist: The power of a scientific mindset", postagem de Santiago Gisler para o blog "Ivory Embassy"
- O que são gêneros acadêmicos?
  - Leitura: "Publique ou pereça", capítulo do livro "Produção textual na universidade", de Désirée Motta-Roth e Graciela Rabuske Hendges.
- Como planejar uma pesquisa? O que é metodologia científica? 
  - Leitura: "A elaboração do projeto", capítulo do livro "Guia do trabalho científico: do projeto à redação final", de Celso Ferrarezi Jr.

### 21/04/2025 (Seg)
- Feriado - Tiradentes

### 24/04/2025 (Qui)
  - Como planejar uma pesquisa?

### 28/04/2025 (Seg)
- Encontro 4

### 01/05/2025 (Qui)
- (Feriado - Dia do Trabalhador)

### 05/05/2025 (Seg)
- Encontro 5

### 08/05/2025 (Qui)
- Encontro 6

### 12/05/2025 (Seg)
- Encontro 7

### 15/05/2025 (Qui)
- Encontro 8

### 19/05/2025 (Seg)
- Encontro 9

### 22/05/2025 (Qui)
- Encontro 10

### 26/05/2025 (Seg)
- Encontro 11

### 29/05/2025 (Qui)
- Encontro 12

### 02/06/2025 (Seg)
- Encontro 13

### 05/06/2025 (Qui)
- Encontro 14

### 09/06/2025 (Seg)
- Encontro 15

### 12/06/2025 (Qui)
- Encontro 16

### 16/06/2025 (Seg)
- Encontro 17

### 19/06/2025 (Qui)
- (Feriado - Corpus Christi)

### 23/06/2025 (Seg)
- Encontro 18

### 26/06/2025 (Qui)
- Encontro 19

### 30/06/2025 (Seg)
- Encontro 20

### 03/07/2025 (Qui)
- Encontro 21

### 07/07/2025 (Seg)
- Encontro 22

### 10/07/2025 (Qui)
- Encontro 23

### 14/07/2025 (Seg)
- Encontro 24

### 17/07/2025 (Qui)
- Encontro 25

### 21/07/2025 (Seg)
- Encontro 26

### 24/07/2025 (Qui)
- Encontro 27

### 28/07/2025 (Seg)
- Encontro 28

### 31/07/2025 (Qui)
- Encontro 29

### 04/08/2025 (Seg)
- Encontro 30
  - Encerramento da disciplina